### ISSUE TITLE
Hello bro I found the answer of C2W4 is incorrect

### ISSUE THREAD

**Issue by PJBian1** [Zekumoru/Learning-C-Sharp-and-Unity#1]

**Comment by PJBian1** [comment]
<img width="592" alt="截屏2022-01-28 23 44 12" src="https://user-images.githubusercontent.com/54138923/151577146-6fb11025-f8c1-4935-a170-0b6392d7573e.png">

**Comment by Zekumoru** [comment]
I did not touch any other parts of the code and I wrote only where it states I should write. Also it works just fine. Though, I'm impressed as of I did not expect someone will actually find my GitHub learning repository. One more thought, you should be working on the problem yourself but for curiosity sake because I'm only auditing the course but did you submit the file correctly? The `Program.cs` file.

![image](https://user-images.githubusercontent.com/57686690/151666985-e045af3e-82a3-41fa-b2f7-ab878064550d.png)
